### ISSUE TITLE
Sometimes widget doesn't show contents

### ISSUE THREAD

**Issue by eun9805** [GrakovNe/lissen-android#235]
Hi.

I love lissen-android and I use it everyday.

Today, I found this problem.

when I play some audiobooks, widget doesn't show contents.

I use 1.5.4 version.

Here are screenshots.

![Image](https://github.com/user-attachments/assets/580ff40e-7429-460d-b469-3970338244dd)
![Image](https://github.com/user-attachments/assets/405a43a4-a8cc-4531-9583-80e7a8e30175)
When I play "Mr.Mercedes", widget works well.

![Image](https://github.com/user-attachments/assets/dadd76fb-5a66-47ad-b500-233b9a79020f)
![Image](https://github.com/user-attachments/assets/b29e6bfe-feb9-45ed-be0f-db4d4b176b91)
When I play "Morningwood", widget doesn't show contents.

Thanks for great apps.

**Comment by GrakovNe** [comment]
Could you please share the content to reproduce the state?

**Comment by eun9805** [comment]
대용량 첨부 1개 230MB

Morningwood.zip 240937929 ~ 2025/08/12
기한이 있는 파일은 30일 보관 / 100회 다운로드 가능



sorry for late.
here it is. 



네이버 메일 앱에서 보냈습니다.

-----Original Message-----
보낸사람: "Max Grakov" ***@***.***>
받는사람: "GrakovNe/lissen-android" ***@***.***>
참조: "silverB" ***@***.***>,"Author" ***@***.***>
날짜:2025.07.11 오후 11:37:14 (GMT+09:00)
제목: Re: [GrakovNe/lissen-android] Sometimes widget doesn't show contents (Issue #235)

GrakovNe left a comment (GrakovNe/lissen-android#235)
Could you please share the content to reproduce the state?

**Comment by GrakovNe** [comment]
Many thanks, but seems like you missed the links

Could you send files to grakovne@gmail.com as attachments

**Comment by eun9805** [comment]
I sent you email.
Thanks.

**Comment by GrakovNe** [comment]
Fixed in https://github.com/GrakovNe/lissen-android/releases/tag/1.5.8

![Image](https://github.com/user-attachments/assets/05521057-979a-4ff0-a388-88890eff8f83)

**Comment by shifltb** [comment]
I am still having this issue. Podcast content always shows up in the widget, but audiobooks are hit-or-miss. It seems like M4B files are more likely to work than OGG and MP3, but I haven't been able to find a specific correlation for what shows up and what doesn't. Some books just work, others just don't. Let me know what other information would be helpful.

Thank you so much, this is such a fantastic app.
